# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: mcmod-releaser

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/mcmod-releaser
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/Aton-Kish/mcmod-releaser/internal/mcmod-releaser/model.version={{ .Version }}
      - -X github.com/Aton-Kish/mcmod-releaser/internal/mcmod-releaser/model.gitCommit={{ .ShortCommit }}
      - -X github.com/Aton-Kish/mcmod-releaser/internal/mcmod-releaser/model.goVersion={{ .Env.GOVERSION }}
      - -X github.com/Aton-Kish/mcmod-releaser/internal/mcmod-releaser/model.goOS={{ .Os }}
      - -X github.com/Aton-Kish/mcmod-releaser/internal/mcmod-releaser/model.goArch={{ .Arch }}
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
