# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  # install
  install:
    deps:
      - install:go
      - install:pnpm
    aliases:
      - default

  install:go:
    cmds:
      - go install github.com/evilmartians/lefthook/v2@latest
      - lefthook install
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
      - go install github.com/goreleaser/goreleaser/v2@latest
      - go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
    preconditions:
      - which go

  install:pnpm:
    cmds:
      - pnpm install
    preconditions:
      - which pnpm

  # clean
  clean:
    deps:
      - clean:go
      - clean:pnpm

  clean:go:
    cmds:
      - lefthook uninstall
      - rm -f $(go env GOPATH)/bin/lefthook
      - rm -f $(go env GOPATH)/bin/govulncheck
      - rm -f $(go env GOPATH)/bin/golangci-lint
      - rm -f $(go env GOPATH)/bin/goreleaser
      - rm -f $(go env GOPATH)/bin/git-chglog
      - go clean -modcache
    preconditions:
      - which go

  clean:pnpm:
    cmds:
      - rm -rf node_modules .pnpm-store

  # lint
  lint:
    deps:
      - lint:go
      - lint:prettier

  lint:go:
    cmds:
      - golangci-lint run {{ .Options }} ${TARGETS}
    preconditions:
      - which golangci-lint
    env:
      TARGETS: ./...

  lint:prettier:
    cmds:
      - pnpm prettier --check {{ .Options }} ${TARGETS}
    preconditions:
      - which pnpm
    env:
      TARGETS: . !pnpm-lock.yaml

  # format
  format:
    cmds:
      - task: format:go
      - task: format:prettier

  format:go:
    cmds:
      - task: lint:go
        vars:
          Options: --fix

  format:prettier:
    cmds:
      - task: lint:prettier
        vars:
          Options: --write

  # test
  test:
    cmds:
      - go test ./... {{ .Options }}
    preconditions:
      - which go

  coverage:
    cmds:
      - task: test
        vars:
          Options: -cover -coverpkg=./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  # vulnerability check
  vulncheck:
    cmds:
      - govulncheck ./...
    preconditions:
      - which govulncheck

  # build
  build:
    cmds:
      - GOVERSION=$(go env GOVERSION) goreleaser {{ or .SubCommand "build" }} --clean --skip=validate {{ .Options }}
    preconditions:
      - which go
      - which goreleaser

  build:snapshot:
    cmds:
      - task: build
        vars:
          Options: --snapshot

  # archive
  archive:
    cmds:
      - task: build
        vars:
          SubCommand: release
          Options: --skip=publish

  archive:snapshot:
    cmds:
      - task: build
        vars:
          SubCommand: release
          Options: --skip=publish --snapshot

  # changelog
  changelog:
    cmds:
      - git-chglog --config .chglog/config.yaml --output CHANGELOG.md {{ if .NEXT_VERSION }}--next-tag ${NEXT_VERSION}{{ end }}
    preconditions:
      - which git-chglog

  # release
  release:
    cmds:
      - task: changelog
      - git add CHANGELOG.md
      - 'LEFTHOOK=0 git commit -m "docs: updated CHANGELOG for ${NEXT_VERSION}"'
      - git tag ${NEXT_VERSION}
      - git push origin main ${NEXT_VERSION}
    preconditions:
      - which git
      - '[[ "${NEXT_VERSION}" =~ ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$ ]]'
      - '[[ "$(git branch --show-current)" == "main" ]]'
